### ISSUE TITLE
CFChecker requires numpy <= 1.8

### ISSUE THREAD

**Issue by pelson** [RosalynHatcher/CFChecker#1]
The latest version of numpy has completely removed the deprecated old numeric code. CFChecker is still making use of this code, therefore cfchecker doesn't support v1.9 of numpy.

The port should be pretty straight forward - there is only limited use of Numeric, and it looks like it is a 1-to-1 replacement with numpy's ndarray (untested).

**Comment by RosalynHatcher** [comment]
Issue moved to cedadev/cf-checker
